version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: orchestration-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: orchestrationdb

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

    kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ADVERTISED_PORT: 9092

volumes:
  mongo-data: