version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: orchestration-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: orchestrationdb

volumes:
  mongo-data: